# Blog settings
permalink: /blog/:title


# My variables
author: Pankesh Bamotra
name: <span>Pankesh<span style="color:#d3d3d3">.</span><a id="lname" style="font-weight:bold; text-decoration:none">Bamotra</a></span><br/><a href="mailto:pankesh.bamotra@gmail.com" style="text-decoration:none"><span class="suffix"> @gmail.com <i class="fa fa-envelope-o" aria-hidden="true"></i></span></a>
logo: /assets/img/Scottie
logo2: /assets/img/Aristotle
title: Sciontist
keywords: data science, machine learning, life, experience, learning, cmu, carnegie mellon university
description: Personal experiences with machines, life, and nature.
google_verification: y2YP_ez9dBS6EBpQHBdl10cRARPTHz-fAhbh74HFn8E
url: http://sciontist.com
timezone: America/New_York

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# mod switch
nmod: 2
mod_switch: 1


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-time-to-read


# Pagination
paginate: 5


# hacker-news
hnlength: 60
hnn: 4


# ghost
ghostday: Fri


# pursuits
pursuits:
  - title: STAT 365/665 Data Mining and Machine Learning
    uri: http://euler.stat.yale.edu/~tba3/stat665/
    statusicon: fa-star-o
    color: 000000
  - title: 10725 Convex Optimization
    uri: http://www.stat.cmu.edu/~ryantibs/convexopt/
    statusicon: fa-star-o
    color: 000000
  - title: The Elements of Statistical Learning
    uri: http://web.stanford.edu/~hastie/ElemStatLearn/
    statusicon: fa-star-o
    color: 000000


# spotify
# Song: Light through the veins
monday_track: 16d2z3C9eqUyKJVuJ14UlS
