# Blog settings
permalink: /blog/:title


# My variables
author: Pankesh Bamotra
name: Pankesh<span style="color:#d3d3d3">.</span><a id="lname" style="font-weight:bold; text-decoration:none">Bamotra</a><a href="mailto:pankesh.bamotra@gmail.com" style="text-decoration:none"><span class="suffix"> @gmail.com <i class="fa fa-envelope-o" aria-hidden="true"></i></span></a>
logo: /assets/img/Scottie.png
title: Sciontist
keywords: data science, machine learning, life, experience, learning, cmu, carnegie mellon university
description: Personal experiences with data that flows around humans, making sense of it, and learning it's impact.
google_verification: y2YP_ez9dBS6EBpQHBdl10cRARPTHz-fAhbh74HFn8E


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate


# Pagination
paginate: 6
