# Blog settings
permalink: /blog/:title


# My variables
author: Pankesh Bamotra
name: Pankesh<span style="color:#d3d3d3">.</span><a id="lname" style="font-weight:bold; text-decoration:none">Bamotra</a><br/><a href="mailto:pankesh.bamotra@gmail.com" style="text-decoration:none"><span class="suffix"> @gmail.com <i class="fa fa-envelope-o" aria-hidden="true"></i></span></a>
logo: /assets/img/Scottie
logo2: /assets/img/Aristotle
title: Sciontist
keywords: data science, machine learning, life, experience, learning, cmu, carnegie mellon university
description: Personal experiences with machines, life, and nature.
google_verification: y2YP_ez9dBS6EBpQHBdl10cRARPTHz-fAhbh74HFn8E
mod_switch: 0
url: http://sciontist.com
timezone: America/New_York

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-time-to-read


# Pagination
paginate: 5


# hacker-news
hnlength: 60
hnn: 4


# ghost
ghostday: Fri


# pursuits
pursuits:
  - title: Probabilistic Models of Cognition
    uri: https://probmods.org/index.html
  - title: STAT 365/665 Data Mining and Machine Learning
    uri: http://euler.stat.yale.edu/~tba3/stat665/
  - title: CSE 6389 Advanced Topics in ML and Data Mining
    uri: http://ranger.uta.edu/~heng/CSE6389.html
  - title: BerkeleyX: CS105x Introduction to Apache Spark
    uri: https://courses.edx.org/courses/course-v1:BerkeleyX+CS105x+1T2016
