# Blog settings
permalink: /blog/:title


# My variables
name: Pankesh <span style="font-weight:bold">Bamotra</span>
title: Sciontist
keywords: data science, machine learning, life, experience, learning, cmu, carnegie mellon university
description: This blog is about my personal experiences with data that flows around the human lives, making sense of it, stumbling, and learning.
google_verification: y2YP_ez9dBS6EBpQHBdl10cRARPTHz-fAhbh74HFn8E


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
